name: project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  flutter_native_splash: ^2.4.4
  flutter_lints: ^5.0.0
  syncfusion_flutter_charts: ^28.1.38
  http: ^1.3.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#000000" # Background color of splash screen
  image: assets/images and icon/splash2.png # Path to your splash image
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true

  # Assets section for images
  assets:
    - assets/images and icon/
